# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Server' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Server
    pod 'ProtocolBuffers-Swift'

  target 'ServerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ServerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
